[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
image = "0.23"
js-sys = "0.3.72"
console_log = "1.0.0"
log = "0.4"